// src/components/LinkCard.tsx
import { Link as RouterLink } from 'react-router-dom'
import { Star, Archive, MoreVertical, ExternalLink, Edit, Trash2, Sparkles, Clock } from 'lucide-react'
import { useState } from 'react'
import { format } from 'date-fns'
import { Link, LinkSource } from '../types'
import { useLinkStore } from '../store/linkStore'

const sourceIcons: Record<LinkSource, string> = {
  twitter: '𝕏',
  linkedin: 'in',
  youtube: '▶',
  github: '⌘',
  article: '📄',
  news: '📰',
  screenshot: '🖼',
  manual: '🔗',
  other: '🌐'
}

const sourceColors: Record<LinkSource, string> = {
  twitter: 'bg-gray-900',
  linkedin: 'bg-blue-600',
  youtube: 'bg-red-600',
  github: 'bg-gray-800',
  article: 'bg-blue-500',
  news: 'bg-amber-500',
  screenshot: 'bg-indigo-500',
  manual: 'bg-gray-500',
  other: 'bg-gray-400'
}

interface LinkCardProps {
  link: Link
  compact?: boolean
}

export default function LinkCard({ link, compact = false }: LinkCardProps) {
  const [showMenu, setShowMenu] = useState(false)
  const { toggleFavorite, toggleArchive, deleteLink, categories } = useLinkStore()

  const category = categories.find(c => c.id === link.categoryId)

  const handleDelete = () => {
    if (confirm(`Delete "${link.title}"?`)) {
      deleteLink(link.id)
    }
    setShowMenu(false)
  }

  if (compact) {
    return (
      <div className="bg-white rounded-xl p-4 shadow-sm card-hover animate-fadeIn">
        <div className="flex items-start gap-3">
          {/* Source Icon */}
          <div className={`w-10 h-10 ${sourceColors[link.source]} rounded-lg flex items-center justify-center text-white text-sm font-bold flex-shrink-0`}>
            {sourceIcons[link.source]}
          </div>

          {/* Content */}
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              {link.url ? (
                <a
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-medium text-gray-900 hover:text-memora-600 truncate flex items-center gap-1"
                >
                  {link.title}
                  <ExternalLink className="w-3 h-3 flex-shrink-0" />
                </a>
              ) : (
                <span className="font-medium text-gray-900 truncate">{link.title}</span>
              )}
              {link.isFavorite && <Star className="w-4 h-4 text-amber-500 fill-amber-500 flex-shrink-0" />}
            </div>
            <div className="flex items-center gap-2 text-xs text-gray-500">
              {category && (
                <span className="flex items-center gap-1">
                  <div className="w-2 h-2 rounded-full" style={{ backgroundColor: category.color }} />
                  {category.name}
                </span>
              )}
              <span className="flex items-center gap-1">
                <Clock className="w-3 h-3" />
                {format(new Date(link.createdAt), 'MMM d')}
              </span>
            </div>
          </div>

          {/* Actions */}
          <div className="flex items-center gap-1 flex-shrink-0">
            <button
              onClick={() => toggleFavorite(link.id)}
              className={`p-2 rounded-lg transition-all ${
                link.isFavorite ? 'text-amber-500' : 'text-gray-400 hover:text-amber-500 hover:bg-amber-50'
              }`}
            >
              <Star className={`w-4 h-4 ${link.isFavorite ? 'fill-current' : ''}`} />
            </button>
            <RouterLink
              to={`/edit/${link.id}`}
              className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-all"
            >
              <Edit className="w-4 h-4" />
            </RouterLink>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="bg-white rounded-xl shadow-sm overflow-hidden card-hover animate-fadeIn">
      {/* Screenshot Preview */}
      {link.screenshot?.fileUrl && (
        <div className="h-40 bg-gray-100 overflow-hidden">
          <img
            src={link.screenshot.fileUrl}
            alt={link.title}
            className="w-full h-full object-cover"
          />
        </div>
      )}

      {/* Header */}
      <div className="p-4 border-b flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className={`w-10 h-10 ${sourceColors[link.source]} rounded-lg flex items-center justify-center text-white text-sm font-bold`}>
            {sourceIcons[link.source]}
          </div>
          <div>
            <span className="text-xs font-medium text-gray-500 uppercase">{link.source}</span>
            <p className="text-xs text-gray-400">{format(new Date(link.createdAt), 'MMM d, yyyy')}</p>
          </div>
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={() => toggleFavorite(link.id)}
            className={`p-2 rounded-lg transition-all ${
              link.isFavorite ? 'text-amber-500' : 'text-gray-400 hover:text-amber-500 hover:bg-amber-50'
            }`}
          >
            <Star className={`w-5 h-5 ${link.isFavorite ? 'fill-current' : ''}`} />
          </button>
          <div className="relative">
            <button
              onClick={() => setShowMenu(!showMenu)}
              className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-all"
            >
              <MoreVertical className="w-5 h-5" />
            </button>
            {showMenu && (
              <>
                <div className="fixed inset-0 z-10" onClick={() => setShowMenu(false)} />
                <div className="absolute right-0 mt-1 w-48 bg-white rounded-lg shadow-lg border py-1 z-20">
                  <RouterLink
                    to={`/edit/${link.id}`}
                    className="flex items-center gap-2 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50"
                    onClick={() => setShowMenu(false)}
                  >
                    <Edit className="w-4 h-4" />
                    Edit
                  </RouterLink>
                  <button
                    onClick={() => { toggleArchive(link.id); setShowMenu(false); }}
                    className="flex items-center gap-2 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 w-full"
                  >
                    <Archive className="w-4 h-4" />
                    {link.isArchived ? 'Unarchive' : 'Archive'}
                  </button>
                  <hr className="my-1" />
                  <button
                    onClick={handleDelete}
                    className="flex items-center gap-2 px-4 py-2 text-sm text-red-600 hover:bg-red-50 w-full"
                  >
                    <Trash2 className="w-4 h-4" />
                    Delete
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="p-4">
        <h3 className="font-semibold text-gray-900 mb-1">
          {link.url ? (
            <a
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-memora-600 flex items-center gap-1"
            >
              {link.title}
              <ExternalLink className="w-4 h-4" />
            </a>
          ) : (
            link.title
          )}
        </h3>

        {link.description && (
          <p className="text-sm text-gray-600 mb-3 line-clamp-2">{link.description}</p>
        )}

        {/* AI Summary */}
        {link.aiSummary && (
          <div className="bg-green-50 rounded-lg p-3 mb-3">
            <div className="flex items-center gap-1 text-green-700 text-xs font-medium mb-1">
              <Sparkles className="w-3 h-3" />
              AI Summary
            </div>
            <p className="text-sm text-gray-700 line-clamp-2">{link.aiSummary.summary}</p>
          </div>
        )}

        {/* Tags */}
        {link.tags.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mb-3">
            {link.tags.map(tag => (
              <span
                key={tag.id}
                className="tag"
                style={{
                  backgroundColor: `${tag.color}15`,
                  color: tag.color
                }}
              >
                #{tag.name}
              </span>
            ))}
          </div>
        )}

        {/* Status */}
        {link.status === 'pending' && (
          <span className="inline-flex items-center gap-1 text-xs text-amber-600 bg-amber-50 px-2 py-1 rounded-full">
            <Clock className="w-3 h-3" />
            Pending AI processing
          </span>
        )}
      </div>

      {/* Footer */}
      {(link.readCount > 0 || category) && (
        <div className="px-4 py-3 border-t bg-gray-50 flex items-center justify-between text-xs text-gray-500">
          {category && (
            <span className="flex items-center gap-1">
              <div className="w-2 h-2 rounded-full" style={{ backgroundColor: category.color }} />
              {category.name}
            </span>
          )}
          {link.readCount > 0 && (
            <span>{link.readCount} visits</span>
          )}
        </div>
      )}
    </div>
  )
}

// src/app/components/link-card/link-card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Link, LinkStatus } from '../../models/link.model';

@Component({
  selector: 'app-link-card',
  standalone: true,
  imports: [CommonModule, RouterLink],
  template: `
    <div class="link-card" [class.list-view]="viewMode === 'list'" [class.has-summary]="link.aiSummary">
      <!-- Screenshot Preview -->
      <div class="card-image" *ngIf="link.screenshot?.fileUrl">
        <img [src]="link.screenshot.fileUrl" [alt]="link.title">
        <div class="image-overlay">
          <span class="badge bg-info">Screenshot</span>
        </div>
      </div>

      <!-- Card Header -->
      <div class="card-header">
        <div class="source-icon" [ngClass]="'source-' + link.source">
          <i class="bi" [ngClass]="getSourceIcon(link.source)"></i>
        </div>
        <div class="card-meta">
          <span class="source-label">{{ link.source }}</span>
          <span class="date">{{ link.createdAt | date:'mediumDate' }}</span>
        </div>
        <div class="card-actions">
          <button
            class="btn-icon"
            [class.active]="link.isFavorite"
            (click)="onFavoriteClick($event)"
            title="Toggle favorite"
          >
            <i class="bi" [ngClass]="link.isFavorite ? 'bi-star-fill' : 'bi-star'"></i>
          </button>
          <div class="dropdown">
            <button class="btn-icon" data-bs-toggle="dropdown">
              <i class="bi bi-three-dots-vertical"></i>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li>
                <a class="dropdown-item" [routerLink]="['/edit', link.id]">
                  <i class="bi bi-pencil me-2"></i>Edit
                </a>
              </li>
              <li>
                <a class="dropdown-item" (click)="onArchiveClick($event)">
                  <i class="bi bi-archive me-2"></i>
                  {{ link.isArchived ? 'Unarchive' : 'Archive' }}
                </a>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <a class="dropdown-item text-danger" (click)="onDeleteClick($event)">
                  <i class="bi bi-trash me-2"></i>Delete
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Card Body -->
      <div class="card-body">
        <h3 class="card-title">
          <a
            *ngIf="link.url"
            [href]="link.url"
            target="_blank"
            rel="noopener"
            (click)="onLinkClick($event)"
          >
            {{ link.title }}
            <i class="bi bi-box-arrow-up-right"></i>
          </a>
          <span *ngIf="!link.url">{{ link.title }}</span>
        </h3>

        <p class="card-description" *ngIf="link.description">
          {{ link.description }}
        </p>

        <!-- AI Summary -->
        <div class="ai-summary" *ngIf="link.aiSummary">
          <div class="summary-header">
            <i class="bi bi-robot"></i>
            <span>AI Summary</span>
          </div>
          <p class="summary-text">{{ link.aiSummary.summary }}</p>
          <div class="key-points" *ngIf="link.aiSummary.keyPoints?.length">
            <span class="key-point" *ngFor="let point of link.aiSummary.keyPoints.slice(0, 3)">
              {{ point }}
            </span>
          </div>
        </div>

        <!-- Tags -->
        <div class="card-tags" *ngIf="link.tags?.length">
          <span
            *ngFor="let tag of link.tags"
            class="tag"
            [style.backgroundColor]="tag.color + '20'"
            [style.color]="tag.color"
          >
            #{{ tag.name }}
          </span>
        </div>

        <!-- Status Badges -->
        <div class="card-badges">
          <span class="badge bg-warning" *ngIf="link.status === 'pending'">
            <i class="bi bi-hourglass-split me-1"></i>Pending AI
          </span>
          <span class="badge bg-success" *ngIf="link.status === 'processed'">
            <i class="bi bi-check-circle me-1"></i>Processed
          </span>
          <span class="badge bg-secondary" *ngIf="link.isArchived">
            <i class="bi bi-archive me-1"></i>Archived
          </span>
        </div>
      </div>

      <!-- Card Footer -->
      <div class="card-footer">
        <span class="read-count" *ngIf="link.readCount > 0">
          <i class="bi bi-eye me-1"></i>{{ link.readCount }} visits
        </span>
        <span class="last-visited" *ngIf="link.lastVisitedAt">
          Last: {{ link.lastVisitedAt | date:'shortDate' }}
        </span>
      </div>
    </div>
  `,
  styles: [`
    .link-card {
      background: white;
      border-radius: 12px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.08);
      overflow: hidden;
      transition: transform 0.2s, box-shadow 0.2s;
      display: flex;
      flex-direction: column;
    }

    .link-card:hover {
      transform: translateY(-2px);
      box-shadow: 0 4px 16px rgba(0,0,0,0.12);
    }

    /* List View */
    .link-card.list-view {
      flex-direction: row;
      align-items: center;
    }

    .link-card.list-view .card-image {
      width: 120px;
      height: 80px;
      flex-shrink: 0;
    }

    .link-card.list-view .card-body {
      flex: 1;
      padding: 1rem;
    }

    .link-card.list-view .card-header {
      padding: 0.5rem;
    }

    .link-card.list-view .ai-summary {
      display: none;
    }

    /* Card Image */
    .card-image {
      position: relative;
      height: 160px;
      overflow: hidden;
    }

    .card-image img {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }

    .image-overlay {
      position: absolute;
      top: 8px;
      right: 8px;
    }

    /* Card Header */
    .card-header {
      display: flex;
      align-items: center;
      padding: 1rem;
      gap: 0.75rem;
      border-bottom: 1px solid #f3f4f6;
      background: transparent;
    }

    .source-icon {
      width: 36px;
      height: 36px;
      border-radius: 8px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 1rem;
    }

    .source-twitter { background: #e0f2fe; color: #0ea5e9; }
    .source-linkedin { background: #dbeafe; color: #2563eb; }
    .source-youtube { background: #fee2e2; color: #dc2626; }
    .source-github { background: #f3f4f6; color: #374151; }
    .source-article { background: #dbeafe; color: #1d4ed8; }
    .source-news { background: #fef3c7; color: #d97706; }
    .source-screenshot { background: #e0e7ff; color: #6366f1; }
    .source-manual { background: #f3f4f6; color: #6b7280; }
    .source-other { background: #f3f4f6; color: #6b7280; }

    .card-meta {
      flex: 1;
      display: flex;
      flex-direction: column;
      gap: 0.125rem;
    }

    .source-label {
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
      color: #6b7280;
    }

    .date {
      font-size: 0.75rem;
      color: #9ca3af;
    }

    .card-actions {
      display: flex;
      gap: 0.25rem;
    }

    .btn-icon {
      background: none;
      border: none;
      padding: 0.5rem;
      cursor: pointer;
      color: #9ca3af;
      border-radius: 6px;
      transition: all 0.2s;
    }

    .btn-icon:hover {
      background: #f3f4f6;
      color: #374151;
    }

    .btn-icon.active {
      color: #f59e0b;
    }

    /* Card Body */
    .card-body {
      padding: 1rem;
      flex: 1;
    }

    .card-title {
      font-size: 1rem;
      margin: 0 0 0.5rem;
      line-height: 1.4;
    }

    .card-title a {
      color: #1f2937;
      text-decoration: none;
      display: inline-flex;
      align-items: center;
      gap: 0.25rem;
    }

    .card-title a:hover {
      color: #f59e0b;
    }

    .card-title a i {
      font-size: 0.75rem;
      opacity: 0;
      transition: opacity 0.2s;
    }

    .card-title a:hover i {
      opacity: 1;
    }

    .card-description {
      font-size: 0.875rem;
      color: #6b7280;
      margin: 0 0 0.75rem;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }

    /* AI Summary */
    .ai-summary {
      background: #f0fdf4;
      border-radius: 8px;
      padding: 0.75rem;
      margin-bottom: 0.75rem;
    }

    .summary-header {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      font-size: 0.75rem;
      font-weight: 600;
      color: #16a34a;
      margin-bottom: 0.5rem;
    }

    .summary-text {
      font-size: 0.8rem;
      color: #374151;
      margin: 0 0 0.5rem;
      display: -webkit-box;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }

    .key-points {
      display: flex;
      flex-wrap: wrap;
      gap: 0.25rem;
    }

    .key-point {
      font-size: 0.7rem;
      padding: 0.125rem 0.5rem;
      background: white;
      border-radius: 4px;
      color: #15803d;
    }

    /* Tags */
    .card-tags {
      display: flex;
      flex-wrap: wrap;
      gap: 0.375rem;
      margin-bottom: 0.75rem;
    }

    .tag {
      font-size: 0.75rem;
      padding: 0.125rem 0.5rem;
      border-radius: 4px;
    }

    /* Badges */
    .card-badges {
      display: flex;
      flex-wrap: wrap;
      gap: 0.375rem;
    }

    .card-badges .badge {
      font-size: 0.7rem;
      font-weight: 500;
    }

    /* Card Footer */
    .card-footer {
      padding: 0.75rem 1rem;
      border-top: 1px solid #f3f4f6;
      display: flex;
      justify-content: space-between;
      font-size: 0.75rem;
      color: #9ca3af;
      background: transparent;
    }

    .dropdown-item {
      cursor: pointer;
    }
  `]
})
export class LinkCardComponent {
  @Input() link!: Link;
  @Input() viewMode: 'grid' | 'list' = 'grid';

  @Output() onFavorite = new EventEmitter<Link>();
  @Output() onArchive = new EventEmitter<Link>();
  @Output() onDelete = new EventEmitter<Link>();

  getSourceIcon(source: string): string {
    const icons: Record<string, string> = {
      'twitter': 'bi-twitter-x',
      'linkedin': 'bi-linkedin',
      'youtube': 'bi-youtube',
      'github': 'bi-github',
      'article': 'bi-file-text',
      'news': 'bi-newspaper',
      'screenshot': 'bi-image',
      'manual': 'bi-link-45deg',
      'other': 'bi-globe'
    };
    return icons[source] || 'bi-link-45deg';
  }

  onFavoriteClick(event: Event): void {
    event.stopPropagation();
    this.onFavorite.emit(this.link);
  }

  onArchiveClick(event: Event): void {
    event.stopPropagation();
    this.onArchive.emit(this.link);
  }

  onDeleteClick(event: Event): void {
    event.stopPropagation();
    this.onDelete.emit(this.link);
  }

  onLinkClick(event: Event): void {
    // Allow the link to open normally, just for tracking purposes
  }
}
